services:
  frontend:
    image: ghcr.io/YamunaJayakumar-df/diginode-frontend:qa
    ports:
      - "9003:80"
    restart: unless-stopped

  backend:
    image: ghcr.io/YamunaJayakumar-df/diginode-backend:qa
    ports:
      - "9004:3001"
    env_file: .env
    restart: unless-stopped
